use_frameworks!

target 'ISaMaterialLogIn_Example' do
  pod 'ISaMaterialLogIn’, :path => '../'
  pod 'Material', '~> 2.0'

  target 'ISaMaterialLogIn_Tests' do
    inherit! :search_paths
    pod 'FBSnapshotTestCase', ‘2.1.4’

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
     end
    end
  end
 end
end
